import type { Game } from '@/types/game';
import type { MetadataSearchResult } from '@/types/metadata';
import sampleHeroUrl from '@/assets/hero.png';

export { sampleHeroUrl };

export const defaultSettings: Record<string, string> = {
  provider_vndb_enabled: 'true',
  provider_bangumi_enabled: 'true',
  provider_dlsite_enabled: 'true',
  provider_fanza_enabled: 'true',
  provider_ymgal_enabled: 'true',
  ai_base_url: '',
  ai_model: 'gpt-4o-mini',
  ui_accent_color: 'vnite',
  ui_theme_mode: 'dark',
  privacy_hide_hidden: 'false',
  privacy_blur_covers: 'false',
  privacy_filter_reports: 'true',
  save_auto_backup_before_launch: 'false',
  save_auto_backup_after_exit: 'false',
  tray_enabled: 'true',
};

export const mockMetadata: MetadataSearchResult[] = [
  {
    provider: 'vndb',
    id: 'v29443',
    title: '終のステラ',
    url: 'https://vndb.org/v29443',
    imageUrl: null,
    description: '文明崩坏后的世界中，少女与运输员同行的视觉小说。',
    releaseDate: '2022-09-30',
    developers: ['Key'],
    tags: ['Post-apocalyptic', 'Android', 'Kinetic Novel'],
    externalIds: { vndb: 'v29443', bangumi: 'bgm-29443', ymgal: 'ymgal-29443' },
    relevanceScore: 0.98,
    fromVndbSniff: false,
  },
  {
    provider: 'dlsite',
    id: 'RJ01000000',
    title: '星之终途 模拟条目',
    url: 'https://www.dlsite.com/maniax/work/=/product_id/RJ01000000.html',
    imageUrl: null,
    description: 'DLsite mock result for development preview.',
    releaseDate: '2022-09-30',
    developers: ['Key'],
    tags: ['ADV', '全年龄'],
    externalIds: { bangumi: 'bgm-29443', dlsite: 'RJ01000000', ymgal: 'ymgal-29443' },
    relevanceScore: 0.74,
    fromVndbSniff: true,
  },
  {
    provider: 'fanza',
    id: 'key_0001',
    title: '星之终途 FANZA 模拟条目',
    url: 'https://dlsoft.dmm.co.jp/detail/key_0001/',
    imageUrl: null,
    description: 'FANZA mock result for development preview.',
    releaseDate: '2022-09-30',
    developers: ['Key'],
    tags: ['PCゲーム'],
    externalIds: { fanza: 'key_0001' },
    relevanceScore: 0.62,
    fromVndbSniff: false,
  },
];

export const sampleGames: Game[] = [
  {
    id: 'sample-1',
    title: '星之终途',
    originalTitle: '終のステラ',
    aliases: ['[汉化硬盘版] 星之终途 v1.02'],
    developer: 'Key',
    publisher: 'Visual Arts',
    brand: 'Key',
    releaseDate: '2022-09-30',
    description: '末世旅途题材的短篇视觉小说。此条目是浏览器预览用示例数据。',
    notes: '这里可以记录攻略进度、补丁说明、通关感想和个人备注。',
    tags: ['全年龄', '科幻', '短篇'],
    genres: ['Visual Novel'],
    rating: 88,
    ageRating: '全年龄',
    playStatus: 'playing',
    favorite: true,
    hidden: false,
    installPath: 'D:\\Games\\VN\\星之终途',
    executablePath: 'D:\\Games\\VN\\星之终途\\stella.exe',
    workingDirectory: 'D:\\Games\\VN\\星之终途',
    launchArgs: null,
    pathStatus: 'unknown',
    lastPathCheckedAt: null,
    coverImage: sampleHeroUrl,
    bannerImage: sampleHeroUrl,
    backgroundImage: sampleHeroUrl,
    vndbId: 'v29443',
    bangumiId: null,
    dlsiteId: null,
    fanzaId: null,
    ymgalId: null,
    totalPlaySeconds: 12600,
    lastPlayedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample-duplicate-1',
    title: '星之终途 旧导入副本',
    originalTitle: '終のステラ',
    aliases: ['Tsui no Stella old import'],
    developer: null,
    publisher: null,
    brand: 'Key',
    releaseDate: null,
    description: '模拟重复条目：用于维护中心的安全合并预览。',
    notes: null,
    tags: ['待整理'],
    genres: ['Kinetic Novel'],
    rating: null,
    ageRating: null,
    playStatus: 'planned',
    favorite: false,
    hidden: false,
    installPath: 'D:\\Games\\VN\\星之终途-old',
    executablePath: 'D:\\Games\\VN\\星之终途-old\\stella.exe',
    workingDirectory: 'D:\\Games\\VN\\星之终途-old',
    launchArgs: null,
    pathStatus: 'unknown',
    lastPathCheckedAt: null,
    coverImage: null,
    bannerImage: null,
    backgroundImage: null,
    vndbId: 'v29443',
    bangumiId: null,
    dlsiteId: 'RJ01000000',
    fanzaId: null,
    ymgalId: null,
    totalPlaySeconds: 1800,
    lastPlayedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
